# The URL the site will be built for
base_url = "https://salif.github.io/zola-themes-collection/"

default_language = "en"
theme = "linkita-theme"
build_search_index = false
compile_sass = false
generate_feeds = false
generate_robots_txt = false
author = "ztc"
title = "Zola Themes"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "boron"
smart_punctuation = false
external_links_target_blank = true
lazy_async_image = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the RFC3339 datetime of the page in the search index
include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which code point to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

# Wether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
index_format = "elasticlunr_javascript"

[extra]
math = false
mermaid = false
comment = false
relative_urls = true
header_menu_name = "main"
disable_default_favicon = true
header_buttons = ["site_title", "theme_select"]

[extra.style]
# The custom background color
bg_color = "#f6f8fa"
# The custom background color in dark mode
bg_dark_color = "#1d212c"
# Enable header blur
header_blur = false
# The custom header color, only available when `header_blur` is false
header_color = "#f6f8fa"
# The custom header color in dark mode, only available when `header_blur` is false
header_dark_color = "#1d212c"

[extra.menus]
main = [
  { url = "https://github.com/salif/zola-themes-collection", name = "Repository" },
]

[extra.profiles.ztc.open_graph]
image = "screenshot.png"
image_alt = "A screenshot of this website."

[extra.footer]
since = 2024
copyright = "&copy; $YEAR"

[extra.languages.en]
locale = "en_US"

[extra.goatcounter]
endpoint = "https://sgi.goatcounter.com/count"
noscript_prefix = "/zola-themes-collection"
